type:
  apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
  kind: ControllerManagerConfig
manager:
  health:
    healthProbeBindAddress: ":8081"
  metrics:
    bindAddress: 127.0.0.1:8080
  webhook:
    port: 9443
  leaderElection:
    leaderElect: true
    resourceName: d47cd155.github.com
    resourceNamespace: default
elasticsearch:
  enabled: true
#   url: https://quickstart-es-http:9200
#   certificate:
#     secretName: quickstart-es-http-certs-public
#     certificateKey: ca.crt
#   authentication:
#     usernamePasswordSecret:
#       secretName: quickstart-es-elastic-user
#       userName: elastic
kibana:
  enabled: true
#   url: https://quickstart-kb-http:5601
#   certificate:
#     secretName: quickstart-kb-http-certs-public
#     certificateKey: ca.crt
#   authentication:
#     usernamePasswordSecret:
#       secretName: quickstart-es-elastic-user
#       userName: elastic
