# permissions for end users to view elasticsearchinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticsearchinstance-viewer-role
rules:
- apiGroups:
  - es.eck.github.com
  resources:
  - elasticsearchinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - es.eck.github.com
  resources:
  - elasticsearchinstances/status
  verbs:
  - get
