# permissions for end users to edit kibanainstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kibanainstance-editor-role
rules:
- apiGroups:
  - kibana.eck.github.com
  resources:
  - kibanainstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kibana.eck.github.com
  resources:
  - kibanainstances/status
  verbs:
  - get
