# permissions for end users to view kibanainstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kibanainstance-viewer-role
rules:
- apiGroups:
  - kibana.eck.github.com
  resources:
  - kibanainstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kibana.eck.github.com
  resources:
  - kibanainstances/status
  verbs:
  - get
