apiVersion: es.eck.github.com/v1alpha1
kind: Index
metadata:
  name: index-base-sample
spec:
  targetInstance:
    name: elasticsearch-quickstart
  dependencies:
    indexTemplates:
      - indextemplate-sample
  body: |
    {
      "aliases": {
          "index-sample-alias": {}
      }
    }
