apiVersion: es.eck.github.com/v1alpha1
kind: ElasticsearchRole
metadata:
  name: elasticsearchrole-sample
spec:
  targetInstance:
    name: elasticsearch-quickstart
  body: |
    {
      "cluster": ["all"],
      "indices": [
        {
          "names": [ "index-sample"],
          "privileges": ["all"]
        }
      ],
      "metadata" : {
        "version" : 1
      }
    }
