apiVersion: es.eck.github.com/v1alpha1
kind: SnapshotLifecyclePolicy
metadata:
  name: snapshotlifecyclepolicy-sample
spec:
  targetInstance:
    name: elasticsearch-quickstart
  body: |
    {
      "schedule": "0 30 1 * * ?", 
      "name": "<daily-snap-{now/d}>", 
      "repository": "snapshotrepository-sample", 
      "config": { 
        "indices": ["*"], 
        "ignore_unavailable": false,
        "include_global_state": true
      },
      "retention": { 
        "expire_after": "30d", 
        "min_count": 5, 
        "max_count": 50 
      }
    }

