apiVersion: kibana.eck.github.com/v1alpha1
kind: DataView
metadata:
  name: dataview-sample
spec:
  targetInstance:
    name: kibana-quickstart
  space: space-sample
  dependencies:
    - type: lens
      name: lens-sample
  body: |
    {
      "title": "sample-index-*",
      "type": "rollup",
      "typeMeta": {
        "params": {
          "rollup_index": "rollup_logstash"
        },
        "aggs": {
          "terms": {
            "geo.dest": { "agg": "terms" },
            "extension.keyword": { "agg": "terms" },
            "geo.src": { "agg": "terms" },
            "machine.os.keyword": { "agg": "terms" }
          },
          "date_histogram": {
            "@timestamp": {
              "agg": "date_histogram",
              "fixed_interval": "20m",
              "delay": "10m",
              "time_zone": "UTC"
            }
          },
          "avg": {
            "memory": { "agg": "avg" },
            "bytes": { "agg": "avg" }
          },
          "max": { "memory": { "agg": "max" } },
          "min": { "memory": { "agg": "min" } },
          "sum": { "memory": { "agg": "sum" } },
          "value_count": { "memory": { "agg": "value_count" } },
          "histogram": {
            "machine.ram": {
              "agg": "histogram",
              "interval": 5
            }
          }
        }
      }
    }
