apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 8.1.0
  count: 1
  elasticsearchRef:
    name: "quickstart"
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              memory: 256Mi
              cpu: 0.25
            limits:
              memory: 1Gi
              cpu: 1

