apiVersion: kibana.eck.github.com/v1alpha1
kind: IndexPattern
metadata:
  name: indexpattern-sample
spec:
  targetInstance:
    name: kibana-quickstart
  body: |
    {
        "attributes": {
            "title": "index-*",
            "timeFieldName": "@timestamp"
        }
    }

